# Álgebra Matricial con `NumPy`

En este apartado presentamos una manera de cómo realizar operaciones básicas con matrices en Python.

Normalmente se nos define una matriz (real) como un arreglo rectangular de números reales. Aunque esto es correcto y pensarlo así resulta muy útil en la práctica, además de concordar en cierto modo con la sintaxis que utiliza Python para trabajar con ellas, se presenta a continuación una definición un tanto más formal que creemos ayudará al alumno a entender futuras generalizaciones.

**Definición.** Una matriz real $M$ de tamaño $m \times n$ es una función
    \begin{eqnarray*}
        M: I_{m} \times I_{n} \,&\longrightarrow&\, \mathbb{R} \\
            (i,j) \,&\longmapsto&\, M(i,j) \equiv M_{ij},
    \end{eqnarray*}

donde $\,I_{m}=\{1,\ldots,m\}\,$ e $\,I_{n}=\{1,\ldots,n\}\,$ son el conjunto de índices de $m$ y $n$ elementos, respectivamente.

Si bien Python permite trabajar con matrices simbólicas, de momento nos centraremos en matrices númericas, es decir, con entradas enteras y flotantes. Para esto, como antes, primero debemos importar el módulo de `NumPy`. 

**Sintaxis.** Para declarar una matriz en Python vía el módulo de `NumPy` utilizamos un sintaxis análoga a la usada para escribir `arrays`.

In [0]:
import numpy as np

A = np.matrix([[11, 12], [21, 22]])
B = np.matrix([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
C = np.matrix([[1], [2], [3]])
D=np.matrix([[1,2,3]])
print(A, '\n') # Usamos print() para visualizar las matrices que acabamos de definir
print(B, '\n') # Recordemos que \n 'imprime' una nueva línea
print(C,'\n')
print(D)

[[11 12]
 [21 22]] 

[[11 12 13]
 [21 22 23]
 [31 32 33]] 

[[1]
 [2]
 [3]] 

[[1 2 3]]


## Multiplicación por Escalar

Para multiplicar una matriz por un escalar (real) en `NumPy` se utiliza el operador `*`.

In [0]:
import numpy as np

A1 = np.matrix([[1, 1 , 1], [1, 1, 1], [1, 1, 1]])
print(5*A1, '\n')
print((-1)*A1, '\n')
print(0*A1)

[[5 5 5]
 [5 5 5]
 [5 5 5]] 

[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]] 

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## Suma (Resta)

El módulo de `NumPy` admite dos maneras distintas de sumar (restar) matrices, una utilizando el operador `+` (`-`) y otra con la función `add` (`subtract`).

* Recordemos que la suma (resta) matricial está definida solamente para matrices con la misma dimensión. 

In [0]:
import numpy as np

A2 = np.matrix([[1, 2 , 3], [2, 3, 1]])
B2 = np.matrix([[-1, -2 , -3], [-2, -3, -1]])

# Primera manera:
print('Primera manera:\n')
print(A2 + B2, '\n')
print(A2 - B2, '\n')

# Segunda manera:
print('Segunda manera:\n')
print(np.add(A2, B2), '\n')
print(np.subtract(A2, B2))

Primera manera:

[[0 0 0]
 [0 0 0]] 

[[2 4 6]
 [4 6 2]] 

Segunda manera:

[[0 0 0]
 [0 0 0]] 

[[2 4 6]
 [4 6 2]]


## Multiplicación

El módulo de `NumPy` admite dos maneras distintas de multiplicar matrices, una utilizando el operador `*` y otra con la función `dot`.

* Recordemos que la multiplicación matricial está definida solamente entre matrices tales que el número de columnas del primer término de la multiplicación coincide con el número de filas del segundo.

In [0]:
import numpy as np

A3 = np.matrix([[1, 2 , 3], [-2, -3, -1]])
B3 = np.matrix([[1, 1], [1, 1], [1, 1]])

# Primera manera:
print('Primera manera:\n')
print(B3*A3, '\n')

# Segunda manera:
print('Segunda manera:\n')
print(np.dot(A3, B3), '\n')

Primera manera:

[[-1 -1  2]
 [-1 -1  2]
 [-1 -1  2]] 

Segunda manera:

[[ 6  6]
 [-6 -6]] 



## Determinante

Para calcular el determinante de una matriz en `NumPy` debemos utilizar el la función `det` del submódulo `linalg`. Este submódulo nos proveé diversas herramientas para manipular y realizar operaciones más 'sofisticadas' con matrices.

* Recordemos que el determinante solamente está definida para matrices cuadradas.

In [0]:
import numpy as np

A4 = np.matrix([[0, -1], [0, 0]])

B4 = np.matrix([[1, 1, 1], [0, 2, 2], [0, 0, 3]])

C4 = np.matrix([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 
                [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
                [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
                [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
                [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
                [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],])


print(np.linalg.det(A4))
print(np.linalg.det(B4))
print(np.linalg.det(C4))

0.0
6.0
1.0


## Matriz Inversa

Si una matriz es invertible, para calcular su inversa en `NumPy` podemos utilizar la función `inv` del submódulo `linalg`.

In [0]:
import numpy as np

# A5 = np.matrix([[0, -1], [0, 0]])

B5 = np.matrix([[1, 1, 1], [0, 2, 2], [0, 0, 3]])

C5 = np.matrix([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 
                [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
                [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
                [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
                [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
                [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],])


# print(np.linalg.inv(A5))
print(np.linalg.inv(B5), '\n')
print(np.linalg.inv(C5))

[[ 1.         -0.5         0.        ]
 [ 0.          0.5        -0.33333333]
 [ 0.          0.          0.33333333]] 

[[ 1. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [0]:
B=np.linalg.inv(B5)

In [0]:
B5*B

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## Matriz Traspuesta

Para calcular la traspuesta de una matriz en `NumPy` podemos utilizar la función `transpose`.

In [0]:
import numpy as np

A6 = np.matrix([1, 2])
print(A6, '\n')
print(np.transpose(A6))

[[1 2]] 

[[1]
 [2]]


In [0]:
import numpy as np

B6 = np.matrix([[1], [2]])
print(B6, '\n')
print(np.transpose(B6))

[[1]
 [2]] 

[[1 2]]


In [0]:
import numpy as np

B6 = np.matrix([[11, 12, 13, 14, 15], [21, 22, 23, 24, 25], [31, 32, 33, 34, 35]])
print(B6, '\n')
print(np.transpose(B6))

[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]] 

[[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]
 [15 25 35]]


## Solución de Sistemas de Ecuaciones Lineales

Una de las herramientas más útiles del submódulo `linalg` es la función `solve`, la cual nos permite encontrar (si existe) una solución $x$ a un sistema de ecuaciones
    \begin{equation*}
        Mx = b,
    \end{equation*}

donde $M$ es una matriz cuadrada de tamaño $\,n \times n\,$ y $\,x,b\,$ son vectores columna de tamaño $n \times 1$.

* La función `solve` recibe dos argumentos, el primero debe ser la matriz $M$ y el segundo el vector $b$. En caso de existir solución, esta función retorna el vector solución $x$.

**Ejemplo.** Consideremos el sistema de ecuaciones
    \begin{align*}
        2x_{1} - x_{2} \,&= \ \ \ 1, \\ 
        -x_{1} + x_{2} \,&= -1,
    \end{align*}
el cual puede escribirse de manera matricial por
    \begin{equation*}
        \left(
            \begin{array}{rr}
                2 & -1 \\
                -1 & 1 \\
            \end{array}
        \right)
        \left(
            \begin{array}{c}
                x_{1} \\
                x_{2} \\
            \end{array}
        \right)
            =
        \left(
            \begin{array}{r}
                1 \\
                -1 \\
            \end{array}
        \right).
    \end{equation*}
Por tanto, en este caso se tiene que
    \begin{equation*}
        M = \left(
            \begin{array}{rr}
                2 & -1 \\
                -1 & 1 \\
            \end{array}
        \right) 
            \qquad \text{y} \qquad
        b = \left(
            \begin{array}{r}
                1 \\
                -1 \\
            \end{array}
        \right).
    \end{equation*}

In [2]:
import numpy as np

M = np.matrix([[3, 2,-1], [2,0, -1],[1,5,1]]) # Declaramos la matriz M
b = np.matrix([[7], [2],[2]]) # Declaramos el vector b

print(np.linalg.solve(M, b)) # Resolvemos el sistema Mx=b

[[-17.]
 [ 11.]
 [-36.]]


Esto nos dice que la solución $x$ de nuestro sistema es
    \begin{equation*}
        x = \left(
            \begin{array}{c}
                x_{1} \\
                x_{2} \\
            \end{array}
        \right)
            =
        \left(
            \begin{array}{r}
                0 \\
                -1 \\
            \end{array}
        \right).
    \end{equation*}

__Ejercicio 1:__ Demuestra que el siguiente conjunto de vectores es linealmente independiente:

$$\{(1,2,-1), (0,1,0), (-3,0,-2)\}$$

Para que el conjunto de vectores sea linealmente independientes, no existirá una combinación lineal no trivial tal que

$(0, 0, -0) = a(1 + 2 - 1) + b(0 + 1 + 0) + c(-3 + 0 - 2)$

Siendo $a,b,c \in \Re$, es decir $a=b=c=0$ 

$\implies (0, 0, 0) = (a + 2a - a) + (0 + b + 0) + (-3c + 0 - 2c)$

$\implies (0, 0, 0) = (a + 0 - 3c, 2a + b + 0, -a + 0 - 2c)$


In [3]:
import numpy as np

M= np.matrix ([[1,0,-3], [2,1,0], [-1,0,-2]])
b= np.matrix ([[0], [0], [0]]) 
print (np.linalg.solve(M,b))

[[ 0.]
 [-0.]
 [-0.]]


__Ejercicio 2:__ Escribe como combinación lineal de los vectores del ejercicio 1 el siguiente vector: 
$$(5,7,-3)$$

El vector A = (5, 7, -3), se puede expresar como combinación lineal de los vectores 

$x = a[1, 2, -1]$

$y = b[0, 1, 0]$

$z = c[-3, 0, -2]$

$\implies (5, 7, -3) = a(1 + 2 - 1) + b(0 + 1 + 0) + c(-3 + 0 - 2)$

$\implies (5, 7, -3) = (a + 2a - a) + (0 + b + 0) + (-3c + 0 - 2c)$

$\implies (5, 7, -3) = (a + 0 - 3c, 2a + b + 0, -a + 0 - 2c)$

En una matriz se expresaría el sistema como

([1  0 -3]
 
 [2  1 0]
 
 [-1  0 -2]) 

La solución da:

([3.8]

 [-0.6]
 
[-0.4]) 

Por lo tanto $a=3.8$, $b=-0.6$ y $c= -0.4$
 

__Ejercicio 3:__ Utiliza la función `solve` para resolver el sistema de ecuaciones del ejercicio 2.

In [5]:
import numpy as np
c= np.matrix([[5],[7],[-3]])
print (np.linalg.solve(M,c))

[[ 3.8]
 [-0.6]
 [-0.4]]
